### ISSUE TITLE
10 * Meter doesn't compile when using Boost Units so Real(10) * Meter is used instead

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#103]
### Expected/Desired Behavior or Experience:
Multiplication accepts `int` and `boost::units::quantity`-types. Or any arithmetic type multiplied with a boost quantity. Division accepts a boost quantity divided by any arithmetic type.

### Actual Behavior:
Multiplication and division operators aren't available to support anything but `Real * quantity` or `quantity / Real`. Always having to cast non-`Real` types to `Real` is annoying.

**Comment by Hexlord** [comment]
I think solution to be made is [here](https://github.com/boostorg/units/blob/37d64605e3f6e2f67038ef9f4eca279518349e99/include/boost/units/heterogeneous_system.hpp#L170), but looking at all those internals makes me think the performance impact is decent with all these structs and checks.

**Comment by louis-langholtz** [comment]
This seems like a reasonable feature so long as the declared type of the result (sans units) is still `Real`. I.e. this is reasonable so long as `decltype(Real{} * X{}) == Real` and `decltype(Real{} / X{}) == Real` where `X` is the arithmetic type. This way if `Real` is `float`: `10 * Meter` or `10.0f * Meter` is okay, but `10.0l * Meter` is an error since a `long double` multiplied by `float` is a `long double` not a `float` anymore.

**Comment by louis-langholtz** [comment]
@Hexlord Already solved this by the way, just trying to document its justification. 😉

**Comment by louis-langholtz** [comment]
Note this effects issue #20 (and Documentation in general).

**Comment by louis-langholtz** [comment]
Resolved now with the referenced and merged commit.
