### ISSUE TITLE
Rewrite manual as online user guide.

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#20]
### Expected/Desired Behavior or Experience:
A user guide would be available from https://louis-langholtz.github.io/PlayRho/ that basically provides the information found in [Documentation/manual.docx](https://github.com/louis-langholtz/PlayRho/blob/master/Documentation/manual.docx). This should not be in DOCX format but  a web page format like HTML (preferably from markdown).

### Actual Behavior:
[Documentation/manual.docx](https://github.com/louis-langholtz/PlayRho/blob/master/Documentation/manual.docx) currently applies to Erin Catto's Box2D from 2.3.2. While many of the concepts may be the same, most - if not all - of the API names have changed. Also much of the interface's inputs, outputs, and I/O parameters have changed.

### Steps to Reproduce the Actual Behavior:
See [Documentation/manual.docx](https://github.com/louis-langholtz/PlayRho/blob/master/Documentation/manual.docx).

**Comment by louis-langholtz** [comment]
I like the way the CppCoreGuidelines [gh-pages](https://github.com/isocpp/CppCoreGuidelines/tree/gh-pages) uses GitHub markdown for their documentation.

**Comment by NauticalMile64** [comment]
I would like to help with this, primarily on the content of the manual, but I don't know the first thing about web development. If you can help me sort out the technical aspects of getting this working so I can just produce the content in a set of markdown files that would be great.

**Comment by louis-langholtz** [comment]
Cool: I'd love help with this!

I started on this by adding an initial User Guide in markdown: [PlayRho/Documentation/UserGuide.md](https://github.com/louis-langholtz/PlayRho/blob/master/Documentation/UserGuide.md). So no need to consider the web dev aspect. I was basically copying and modifying from the PDF of the docx file into the user guide and then using the limited tagging of markdown to add some formatting to the pasted text.

For textual transformations:

1. I replaced instances of *Box2D* with *PlayRho*.
2. I replaced *judgmental* terms with *relative* terms/phrases. This one's harder for me to explain and I don't know how meaningful this change is to others. It is important to me though perhaps as addressing a pet peeve I have with user guides. As an example, instead of saying absolute and assertive-upon-the-reader terms like *it's easy*, *good*, *bad*... I prefer phrases like "meant to make physics programming *easier*", "things are likely to react *better* with", or "results may be *less desirable*". Is there a term in writing that encapsulates this different style?
3. I didn't copy over images and for the beta release skipping those is acceptable to me.

BTW... markdown seems pretty ideal to me for integrating with Jekyll which is what's used at the `gh-pages`-based web documentation at https://louis-langholtz.github.io/PlayRho/ .

**Comment by louis-langholtz** [comment]
@NauticalMile64 Is this something you want to work on?

I recall that I'd started working on this before I'd seen that you'd expressed some interest in it. Oh, and I also recall, that you'd made some animated GIFs that I looked *really fantastic* to me especially for explaining visually what some capabilities did! :smiley:

Now that the squishy issue is resolved (and it's now less squishy than I've seen in any other implementation) I'm reviewing these other older issues and wanting to prioritize getting them finished for beta release.

**Comment by NauticalMile64** [comment]
@louis-langholtz Yes, I would still like to work on this, thanks for the reminder! I got a little distracted at the time by the joint renaming, and issues with joints in general, and then life got in the way.

That being said, I'll start with the world, shape, fixture, and body creation routines. I see that as the minimum anyone needs to get started with PlayRho. Then we can critique the content, format, and style. to come up with something that everyone is happy with.

**Comment by NauticalMile64** [comment]
Is there a target date for the beta launch?

**Comment by louis-langholtz** [comment]
@NauticalMile64 No. There's no target date for beta launch at the moment. There's just the issues associated with the beta launch. After those issues are all closed, I'll have the beta launch occur.

If you're asking in order to plan your time: I still have some issues in this milestone that I've assigned to myself but as I get done with those I'll start looking to work on issues that haven't been resolved yet but are in the beta launch target.

Incidentally (like for anyone reading this who's not already aware), the beta launch is the [Beta Launch Milestone](https://github.com/louis-langholtz/PlayRho/milestone/1) that I've setup in [GitHub's Milestones web interface](https://github.com/louis-langholtz/PlayRho/milestones). I can set the "due date" for it -- which would be the target date for it -- but I haven't set one.

**Comment by louis-langholtz** [comment]
@NauticalMile64 Are you planning on doing a full re-write of the user guide? I ask because I could finish simply rewriting the Box2D manual as markdown for the Beta Release, and if you are doing a rewrite then that could be pushed out perhaps till Release 1.0 then as a separate issue/task. We could open the separate issue then as something like "User Guide Needs Improvement" and target it for 1.0. That'd give you more time. That only seems to work though if you're planning to effectively do a full rewrite. What are your thoughts?

**Comment by louis-langholtz** [comment]
As time goes by I'm disliking this manual more and more. I think the main problem I'm having with it is it all coming manually in the form of one single file. I thought it'd be easy enough to just substitute PlayRho names for Box2D names but that's not sitting well enough with me.

I'd prefer to do something fundamentally different for a user guide. Not sure what however. Using doxygen and generating a user guide out of doxygen comments would be preferable at this point even though it seems most aligned with generating API type docs.

**Comment by NauticalMile64** [comment]
I think the entity editor has in some ways made the user guide obsolete already. The user guide was supposed to fill a gap between the documentation and the Testbed; it provides some detailed information but it's also accessible. That gap is now significantly smaller, which may be why you are falling out of love with the idea.

**Comment by louis-langholtz** [comment]
@NauticalMile64 Thank you for your response. I agree wholeheartedly with your assessment!

I'm closing this issue in favor of removing the user guide (`Documentation/UserGuide.md`), removing the Word Doc based manual (`Documentation/manual.docx`), and focusing the effort on the API documentation (see issue #21 and the [Documentation work](https://github.com/louis-langholtz/PlayRho/projects/4) project) and the `Testbed` application.
