### ISSUE TITLE
Confusing ShapeDefs/Confs

### ISSUE THREAD

**Issue by ninnghazad** [louis-langholtz/PlayRho#223]
So was starting some migrating over the weekend and while writing some serialization-functions i need to replicate PlayRho objects from saves and/or network, i got confused.
I do not want to change the PlayRho-source to add my serializers to the classes, so i have external voids that take the subjects as params. Which kind of means i am restricted to use a public interface to get stuff in/out of the PlayRho classes. 
While doing the `ShapeDef`, `PolygonShape::Conf` confuses me.
`ChainShape` ie has public vertices - nice, i can just de/serialize that in my functions. Now for `PolygonShape` - it's vertices are private, or, well not mentioned in the ::Conf it seems.
Is there are reason for this difference?

**Comment by louis-langholtz** [comment]
Sorry about the confusion and I really appreciate your bringing it to my attention!

As for reason for the difference, something that comes to mind right now is that the polygon shape class has invariants like the following:

1. It's vertices must be in counter-clockwise order.
1. Vertices must define a convex polygon.

While the chain shape class doesn't have those invariants. These invariants I think only need to apply to the polygon and chain shape classes however and as such wouldn't explain nor necessitate a difference between the configuration classes (for those shape classes).

Do you have a preference between being able to set the vertices on construction of the polygon shape class versus using a setter method like `PolygonShape::Set(Span<const Length2> points)`?

I think part of the confusion and part of what I dislike about the shape classes is how there's an inconsistent mix of configuration on construction and modification of instances that can be done with them. I've been thinking about how to deal with this problem but it's not been a priority of late and I believe it could benefit from feedback/direction from users and desired use cases.

**Comment by ninnghazad** [comment]
Hm, i think my preference (defined by my current use) would be to be able to pack a simple config/definition with all that is needed for that body, and use that to construct it. 
That makes all the deferred construction that is needed for the networking, file-save/load and script-bindings easier. 
I would also argue that setting vertices on construction is the proper way because they are not supposed to be changed after construction (at least i think that was the case with box2d).
Guess that might also enable one to make certain assumptions that spares a check here or there, like there can never be a polygon without points, because you couldn't even construct one. (no idea if this is a thing with playrho.)

The moment i create the information what body to spawn, is basically never the moment i actually create the body. And the information needed to do so, i have to store and pass around. Same for joints.

**Comment by Hexlord** [comment]
Definition is a good thing as you often create same shape objects.

My engine handles some destructibility and replicates point array inside a class to manage them on collision, so it would be useful to at least have something like PolygonShape::ExtractGeometry(&where) or provide const accessor via iterator or smth, this could save some memory for some people.

Maybe implementing some sort of DefinitionFactory or GeometryMapper would allow to both resolve this inconsistency and allow further implementation of SOA approach to boost the performance.

**Comment by louis-langholtz** [comment]
@ninnghazad 

Your point about setting vertices on construction since they're not to be changed after construction is particularly valid for PlayRho since PlayRho even shares shape definitions.

Shape instances in turn tie in to child shapes (i.e. `DistanceProxy` instances). Because the child shapes are extremely performance critical, that prevents some changes that might clear things up from being viable. This is part of an ongoing debate I've been having about this issue.

I can remove any and all mutating methods from `Shape` subclasses and make sure they could all be 100% configurable at construction time without bumping up against deeper issues I have with the shape classes (in both Box2D and PlayRho actually). I probably **should** get rid of those methods anyway. I believe I can always turn their functionality into free functions that either worked on the configuration classes or returned configuration instances from shapes that they replicate from.

**Comment by louis-langholtz** [comment]
With the merge of pull request #237, all of the mutating functionality has been moved out from the `Shape` classes and moved into their respective configuration classes. Please take a look and let me know what you think of the changes.

**Comment by louis-langholtz** [comment]
With my last code merge, all the `*Def` names have been renamed `*Conf`. So there's no longer ShapeDefs and ShapeConfs; just ShapeConfs so to speak. Closing this issue now. If the other issue of confusion about how to use shape configurations is still a problem, either let me know and I'll open a separate issue for it or go ahead and open such an issue directly.
