### ISSUE TITLE
Unit test - gtest-printers hash_map and hash_set elevated warnings

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#24]
### Expected/Desired Behavior or Experience:
gtest-printers builds as expected.

### Actual Behavior:
gtest-printers fails with errors:

> C2338 <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	gtest-printers_test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\hash_map	18	

> C2338 <hash_set> is deprecated and will be REMOVED. Please use <unordered_set>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	gtest-printers_test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\hash_set	18	

### Steps to Reproduce the Actual Behavior:
Build the unit tests with Windows 10, VS 2017 project generated using CMake 3.9.0 . Not sure if this is a Windows-specific issue.

**Comment by NauticalMile64** [comment]
Ok, after looking into this, it seems to be an issue with google/googletest#823 . Which is supposed to be resolved by pull request google/googletest#811 ... which hasn't been merged yet 😑.

**Comment by NauticalMile64** [comment]
Hmm... despite the above issue and pr, [This commit](https://github.com/google/googletest/commit/518e0519ca49c3a6504d1e377c5a467434d5f719) actually solved this issue. I've manually applied those commit changes, and verified that the project builds. This commit was part of a pr which was merged on May 2, while this project references a snapshot last updated on Feb 25.

Is the googletest folder just a git submodule which needs to be updated? Is there a reason you want to work with a static version of that repo?

**Comment by louis-langholtz** [comment]
@NauticalMile64 Yes. The googletest folder is just a git submodule. I have no objection to updating it so long as whatever it's updated to doesn't cause more issues in total.

BTW, there's a related issue to this: [Repo using submodule.Box2D](https://github.com/louis-langholtz/PlayRho/issues/23). Err, well, related in the sense that if the googletest folder submodule reference is updated, I'd like to get rid of this holdover from Box2D issue.

**Comment by louis-langholtz** [comment]
Commit 6ec78823a784ef238c4a17d6bc8123a5ccb1b2a6 deleted the older googletest submodule and replaced it with [googletest @ e5b88b2](https://github.com/google/googletest/tree/e5b88b227e6adfa7196575b1264384e718d16cab).

@NauticalMile64 Does this update help with what you're seeing?

**Comment by NauticalMile64** [comment]
@louis-langholtz Yes. The error is resolved now, thank you. I just had to use `git submodule update` after pulling in your changes.
