### ISSUE TITLE
Joint class designed for public inheritance.

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#288]
### Expected/Desired Behavior or Experience:
`Joint` class is designed for on-use polymorphism instead of public sub-classing. Then the `Joint` class has no sub-classes: `DistanceJoint`, `FrictionJoint`, `GearJoint`, `MotorJoint`, `PrismaticJoint`, `PulleyJoint`, `RevoluteJoint`, `RopeJoint`, `TargetJoint`, `WeldJoint`, and `WheelJoint` all go away.

### Actual Behavior:
`Joint` class is an abstract base class that has to be sub-classed to be used.

### References:
- See: [Sean Parent's talk "Inheritance Is the Base Class of Evil"](https://channel9.msdn.com/Events/GoingNative/2013/Inheritance-Is-The-Base-Class-of-Evil).
- StackOverflow Q&A for ["Clarification about Sean Parent's talk 'Inheritance is the base class of evil'"](https://stackoverflow.com/questions/26199126/clarification-about-sean-parents-talk-inheritance-is-the-base-class-of-evil).

### Perceived Challenges:
Currently the `World::CreateJoint` method returns a handle to the created joint that's a pointer to the memory that's owned and managed by the world instance. That arguably defeats the purpose of moving from public inheritance to on-use polymorphism. So to redesign the joint class to do away with public inheritance it may make more sense to first redesign the library interface so that world instances return opaque handles for created entities which users have to call the world instance to actually access. That's potentially a bigger task though.

**Comment by NauticalMile64** [comment]
I watched the video and I get the gist of it, but I'm having trouble seeing how this applies to PlayRho joints. Would the users (clients) implement their own joint class and pass instances of it to the `world` object? How can we trust the users to implement all the methods required? I can understand how advanced users might be able to write their own joint class, but the average user just wants to pass the joint parameters to box2d and be done with it.

**Comment by louis-langholtz** [comment]
I love these questions! Thank you!

I'd like the design of joints to become more like the design of shapes. So users wouldn't have to implement joint code any more than shape code. They still could though if they wanted to.

In practice, I'm foreseeing users still using joint configurations. Those would still get passed to the world instance in a create joint request. What gets returned would be more like a unique key however; not a memory address.

If users wanted to create their own joint types, they would still have to implement the methods expected. The compiler enforces that still. Except the methods are pure functions. And as such, it is easier to write more isolated and complete unit test code for.

With the redesign, users would still have the same end functionality but the interfaces would look different. That's because they will ask the world for access to the joint configuration of a created joint using the previously returned key/ID instead of having more direct access via pointers to the actual joints. I'm figuring that the keys would just be indexes which can reduce memory needs by half or more on 64-bit platforms.

**Comment by louis-langholtz** [comment]
With pull request #346, the `Joint` class no longer has any derived classes. Joints get created using a configuration value whose type provides all the necessary polymorphic behavior of joints. The new design is even user extensible.

The new design borrows on the designs of `Shape` and of `std::any` w.r.t. `std::any::type` and `std::any_cast` but without using `typeid` nor `std::type_info`.

So for example, to create what used to be a `RevoluteJoint`, instead create a `Joint` with the value of a `RevoluteJointConf` instance. I.e. `Joint{RevoluteJointConf{}}`. Of course that won't be as useful as setting up the `RevoluteJointConf` with the values necessary, like what bodies are to be body-A and body-B.

Go polymorphic values!!

Marking this issue as closed.
