### ISSUE TITLE
Unrecognized flag "-O3" warnings on VS2017

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#29]
### Expected/Desired Behavior or Experience:
CMake-generated VS solution builds without issue

### Actual Behavior:
Compiler generates warnings 'Unrecognized flag "-O3"' when building.

--------
I noticed there are a few lines in PlayRho/CMakeLists.txt:

```
# Tell C++ compiler to optimize release builds for speed.
# In clang++, the optimize for speed flag is '-Ot'. This option isn't supported on g++
# however and it'd be nice to use an option that works for both compilers. So use '-O3'.
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3" )
```

Omitting the `-O3`  eliminates the warnings.

Can I create a clause so that for the Visual Studio configurations this flag is omitted?

**Comment by louis-langholtz** [comment]
Sounds like the `CMakeLists.txt` file needs an if-not-Windows conditional for setting the `CMAKE_CXX_FLAGS_RELEASE` parameter with the `-O3` flag. Are you familiar with writing CMakeList.txt file [command syntax](https://cmake.org/cmake/help/v3.4/command/if.html)?

Something like:

    if(NOT MSVC)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3" )
    endif(NOT MSVC)

Is probably what's needed.

**Comment by NauticalMile64** [comment]
Well I'm getting familiar with it now. I'll submit a pr soon with this fix and a couple of cleanups.
