### ISSUE TITLE
No external fixed-point implementation supported.

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#295]
### Expected/Desired Behavior or Experience:
A well-tested fixed-point type from another project is supported for use by this project. Ideally this fixed-point type is implemented in C++, is `constexpr` enhanced, satisfies the `LiteralType` concept, and can fully support 64-bit fixed point math.

### Actual Behavior:
While I've developed support for a fixed-point type (see `playrho::Fixed`) including mathematical function support for it, there's no known external implementations that are also supported.

The implementation I've done for `Fixed64` also has what I'll call shortcomings:
- It's not in wide use with wide testing.
- It relies on a 128-bit integer type being supported on the platform which isn't common enough.
- The implementation of mathematical functions like `log` and `exp` I believe to be inferior to implementations like of the [CORDIC algorithm](https://en.wikipedia.org/wiki/CORDIC).

The use of `Fixed32` has even worse shortcomings IMO.

### Interesting Candidates:
- https://github.com/BoostGSoC15/fixed_point
- https://github.com/johnmcfarlane/cnl : this is just in early stage but looks promising.

**Comment by rjdgtn** [comment]
Take a look at johnmcfarlane/fixed_point. It uses constexpr and as a whole looks like modern c++ library.

**Comment by rjdgtn** [comment]
I just tried libfixmath (https://code.google.com/archive/p/libfixmath/). It's not use constexpr, so i take original box2d, slightly modify the libfixmath and switch typedefs float32 and float64 to Fix16 (and few other changes). 
Result looks deterministic in my tests and about x5 faster then PlayRho with Fixed32 on my tasks.

I can publish my patched box2d and libfixmath if you find it useful.

**Comment by louis-langholtz** [comment]
WikiPedia has an entry for [libfixmath](https://en.wikipedia.org/wiki/Libfixmath). https://github.com/PetteriAimonen/libfixmath is where the Wikipedia entry points to for the Website.

I recall reading that it had impressive performance. I believe it's limited however to [Q16.16](https://en.wikipedia.org/wiki/Q_(number_format)) format. Do you know if that's correct?

It's not `constexpr` enhanced as you pointed out which causes ripple effects into lots of other code in PlayRho which relied on that to in turn also be `constexpr` functions. I'd added the `PLAYRHO_CONSTEXPR` macro to help with avoiding needing lots more code changes by simply redefining its value to nothing. So I think that wouldn't be a stopper for using libfixmath at this point.

`Fixed32` uses what I believe would be called Q23.9 format (in having 9 bits used for the fraction bits and the remaining 23 bits used for the integer bits). A reason I chose more integer bits was because that seemed to better favor the scale recommended by Erin for Box2D in terms of MKS units. If `libfixmath` isn't hard wired to 16.16 do you know if it could also support 23.9?

I'm looking into these things but figured I'd explain that in case you knew already.

Incidentally, I believe there's a GNU C fixed point implementation that's also quite speedy and well tested that perhaps would be appealing.

**Comment by rjdgtn** [comment]
libfixmath is rigidly bound to Q16.16 format. It is old style, hard writed library without any templates. Change to Q23.9 means rewriting almost the entire library.

**Comment by ninnghazad** [comment]
Tried using CNL with PlayRho, but CNL automatically widens types to prevent overflows on multiplications. PlayRho did not like that. Could not see an easy way to forbid CNL to change it's underlying type on multiplication. Still, looks CNL looks good apart from that.

**Comment by louis-langholtz** [comment]
With pull #537, the CMake configuration now supports the following additional user settable variables:

- `PLAYRHO_REAL_LINEARSLOP` - to override the `DefaultLinearSlop` value in [`Settings.hpp`](https://github.com/louis-langholtz/PlayRho/blob/d07ab4ac70a95f69b06aba8df0e9a08bfcaa45b2/Library/include/playrho/Settings.hpp) generated from `Settings.hpp.in`.
- `PLAYRHO_REAL_MINVERTEXRADIUS` - to override the `DefaultMinVertexRadius` value in [`Settings.hpp`](https://github.com/louis-langholtz/PlayRho/blob/d07ab4ac70a95f69b06aba8df0e9a08bfcaa45b2/Library/include/playrho/Settings.hpp) generated from `Settings.hpp.in`.
- `PLAYRHO_REAL_MAXVERTEXRADIUS` - to override the `DefaultMaxVertexRadius` value in [`Settings.hpp`](https://github.com/louis-langholtz/PlayRho/blob/d07ab4ac70a95f69b06aba8df0e9a08bfcaa45b2/Library/include/playrho/Settings.hpp) generated from `Settings.hpp.in`.
- `PLAYRHO_REAL_INCLUDE` - to insert user specified includes into the `Real.hpp` file generated from `Real.hpp.in`.

**Comment by louis-langholtz** [comment]
With pull #538, the CMake configuration also supports these settings:

- `PLAYRHO_REAL_FETCH`: names a package for CMake to fetch.
- `PLAYRHO_REAL_GIT_REPOSITORY`: specifies git repository to fetch from.
- `PLAYRHO_REAL_GIT_TAG`: specifies tag of git sources to actually get.

And the following was able to configure, build, and install:

```
CC=/opt/homebrew/opt/llvm/bin/clang \
CXX=/opt/homebrew/opt/llvm/bin/clang++ \
LDFLAGS='-L/opt/homebrew/opt/llvm/lib/c++' \
cmake -S PlayRho -B PlayRhoBuild \
	-DPLAYRHO_BUILD_UNIT_TESTS=ON \
	-DPLAYRHO_BUILD_BENCHMARK=ON \
	-DPLAYRHO_BUILD_TESTBED=ON \
	-DPLAYRHO_BUILD_HELLOWORLD=ON \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
	-DPLAYRHO_BUILD_DOC=ON \
	-DPLAYRHO_ENABLE_BOOST_UNITS=ON \
	-DPLAYRHO_REAL_TYPE='::realnumb::fixed64' \
	-DPLAYRHO_REAL_INCLUDE='#include <realnumb/fixed.hpp>;#include <realnumb/fixed_math.hpp>;#include <realnumb/fixed_limits.hpp>' \
	-DPLAYRHO_REAL_FETCH=realnumb \
	-DPLAYRHO_REAL_GIT_REPOSITORY=https://github.com/louis-langholtz/realnumb.git \
	-DPLAYRHO_REAL_GIT_TAG=main  \
	-DPLAYRHO_INSTALL=ON \
	-DREALNUMB_INSTALL=ON
```

Next to do, ideally, is to provide support for `find_package` as an alternative to the CMake fetch mechanism.

**Comment by louis-langholtz** [comment]
With PR #539, I'm gonna call this issue completed, with the [realnumb](https://github.com/louis-langholtz/realnumb) project being the external fixed-point implementation supported. With that PR:

- `PLAYRHO_REAL_FETCH` was changed to `PLAYRHO_REAL_PROJECT`.
- `PLAYRHO_REAL_GIT_TAG` is now optional.
- If `PLAYRHO_REAL_GIT_REPOSITORY` is not defined but `PLAYRHO_REAL_PROJECT` is, then CMake will use its `find_package` function to find the package named by the `PLAYRHO_REAL_PROJECT` variable.
