### ISSUE TITLE
NDK Compile error

### ISSUE THREAD

**Issue by XPDT1** [louis-langholtz/PlayRho#319]
Hi @louis-langholtz
I'm going to use only fixed-point feature in old version of Box2d and compile by ndk?
I added Fixed.hpp , Wider.hpp and Templates.hpp files to Common folder and include Fixed.hpp in  b2Settings.h
Now, When compiling with ndk the following error occurs:
```
.../jni/Box2D/Common/Wider.hpp:23:10 fatal error:
'type_traits' file not found
#include <type_traits>
1 error generated.
```
Tested with ndk version 10r , 12b and 16b.

**Comment by XPDT1** [comment]
It is possible to compile PlayRho by NDK? @louis-langholtz

**Comment by louis-langholtz** [comment]
Hi XPDT1. Thank you for asking!

I don't know if it's possible to compile PlayRho by NDK. By NDK, do you mean the [Android Native Development Kit](https://en.wikipedia.org/wiki/Android_software_development#Android_NDK)?

If you're just looking for an implementation of a fixed point data type to use with Box2D, I would imagine that there are better implementations out there than mine. I haven't looked at making my fixed point implementation independently usable either. That's an interesting idea but probably not a priority for me.

Also, I think getting a fixed point data type to replace all uses of float in Box2D would require changes to multiple places in Box2D. From what I recall, it looked like there was an abstract real number type notion in Box2D but over time it appears to have fallen into a less and less supported state.

**Comment by XPDT1** [comment]
Thanks for reply @louis-langholtz
Yes, I mean that Android Native Development Kit.

I tested before [this](https://github.com/lhartmann/fixed_point) in Box2d. It is not complete but i could use it in b2Math.h and it worked. Unfortunately there is bad performance.

You said: 
> I would imagine that there are better implementations out there than mine.
Please introduce me.

**Comment by louis-langholtz** [comment]
Here's some implementations that look interesting to me:
* https://github.com/johnmcfarlane/cnl
* https://github.com/PetteriAimonen/libfixmath

Hope this helps.
