### ISSUE TITLE
Compilation Error in GrowableStack

### ISSUE THREAD

**Issue by erincatto** [louis-langholtz/PlayRho#323]
### Expected/Desired Behavior or Experience:
Tried to compile latest

### Actual Behavior:
Got this error:
PlayRho/Common/GrowableStack.hpp(133): error C3779: 'playrho::GrowableStack<T,N>::GetBufferGrowthRate': a function that returns 'auto' cannot be used before it is defined

### Steps to Reproduce the Actual Behavior:
I built the project using Cmake and VS 2017 x64

**Comment by louis-langholtz** [comment]
Hi Erin,

Sorry about this problem. I have [a commit that fixes this](https://github.com/louis-langholtz/PlayRho/pull/322/commits/4634ff4a23030914f8eb686c142ab545834ec344) but haven't pushed it yet.

Seems something has changed with coverage analysis on the coveralls.io system which has broken coverage analysis for this project. I want to get coverage analysis working again before doing the push. In the meantime, if you want, you can cherry pick that commit I believe.

If anyone has insight into how to fix the coverage analysis problem, please speak up. I'm continuing to work on that in the meantime but don't seem to be making head way yet.

**Comment by louis-langholtz** [comment]
I believe the code changes necessary for fixing this have been merged into master now. My sincerest thanks go out to @ninnghazad who provided critical help with getting that to happen.

While the Windows CI appears to verify the changes just finally merged today didn't break anything new, I'd like to get independent confirmation from any Windows users that the problem @erincatto has reported, indeed is resolved, before I close this issue.

**Comment by louis-langholtz** [comment]
Haven't heard that this problem isn't fixed yet so I'm assuming this is indeed fixed and am closing this issue.
