### ISSUE TITLE
Inquiries regarding rounded corners

### ISSUE THREAD

**Issue by Fusionnist** [louis-langholtz/PlayRho#327]
Hello,

I would firstly like to thank you for your document discussing ways to fix polygon-to-polygon collision mishaps with rounded corners, it is a fix I would like to explore for myself but have very little idea where to look into if I were to start; 
The engine I have been using is a C# port of box2d, VelcroPhysics, and while its architecture must be similar, I straight out do not know how most of its inner aspects function. 
As such, my question is: if I were to try rounded corner solving, where should I focus? Is it better to edit the imported code, or can I pass such an instruction as an argument?
I recognize there might be a better place to ask this question, but did not find anywhere else.

Thank you again for your time and work on this issue!

**Comment by louis-langholtz** [comment]
Hi Fusionnist. Not sure how to answer.

Are you looking to modify [VelcroPhysics](https://github.com/VelcroPhysics/VelcroPhysics) on your own to do the rounded corners calculations or wanting VelcroPhysics to add this as an option? Either way, I'd guess that the rounded corner functionality could be ported to VelcroPhysics though I don't recall now how widespread the changes needed are.

The [`GetManifold`](https://github.com/louis-langholtz/PlayRho/blob/6b3b5d9d3f11ba4625854960dabe359f417d3208/PlayRho/Collision/Manifold.cpp#L100) function may be a good starting point to look at for such an endeavor.

**Comment by louis-langholtz** [comment]
Haven't heard any more on this issue so assuming safe to close now.
