### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [louis-langholtz/PlayRho#330]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “MyDestructionListener::SayGoodbye”](https://github.com/louis-langholtz/PlayRho/blob/6b3b5d9d3f11ba4625854960dabe359f417d3208/Testbed/Tests/iforce2d_TopdownCar.hpp#L357 "Update candidate").

**Comment by ninnghazad** [comment]
While technically correct - after making a quick PR, i realized that not all fixtures in that demo have FixtureUserData assigned. Without testing i would assume removing that nullptr check may try to delete fud even for Fixtures that did not have SetUserData, resulting in bad delete.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/ninnghazad/PlayRho/commit/0c4780571b51538cf709775e823738c64f7c740b "Remove an unnecessary check before delete.").
Would you like to improve the pointer handling at other places any further?

**Comment by louis-langholtz** [comment]
@elfring Thank you for reporting this! The code that you've reference is sort of third party code. I hadn't tried to vet it as thoroughly as PlayRho library code. Never the less, it's awesome to me to see people reviewing any of the code!

**Comment by louis-langholtz** [comment]
Pull request #346, also included changes that removed this unnecessary nullptr check. Thanks again for pointing it out! Marking this as closed now.
