### ISSUE TITLE
Library installation can't be completed.

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/PlayRho#39]
I'm trying to install library to system library path, but at the end of installation I'm getting error message:
```
CMake Error at PlayRho/cmake_install.cmake:201 (file):
  file INSTALL cannot find
  "/home/megaxela/Development/Build/PlayRho/PlayRho/UsePlayRho.cmake".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)


make: *** [Makefile:74: install] Error 1
```
Build files was generated with `cmake 3.8.2` with command `cmake -DPLAYRHO_BUILD_UNIT_TESTS=On -DPLAYRHO_BUILD_TESTBED=On -DPLAYRHO_INSTALL=On -DCMAKE_BUILD_TYPE=Release ..`

### Expected/Desired Behavior or Experience:
Library has to be installed fine.

### Actual Behavior:
Library is installing fine and as for me it's even working fine.

### Steps to Reproduce the Actual Behavior:
Build project with `-DPLAYRHO_INSTALL=On` key on configuration step. Then on `make install` step it'll fail with recently provided error.

**Comment by louis-langholtz** [comment]
@Megaxela any ideas by chance of how to fix this? I'd like the cmake install option to work but I don't know off the top of my head what needs to be done to fix this problem. I'd guess it's something simple like that I misnamed a file or misplaced it in transitioning the project from being called `Box2D` to being called `PlayRho`.

**Comment by Megaxela** [comment]
As for me problem is in `PlayRho/CMakeLists.txt` file in line `152`. You are trying to install `UsePlayRho.cmake` file, but there is no any file with this name in project.

**Comment by louis-langholtz** [comment]
Thanks for looking into this. I was thinking similarly to you on this I believe. I'm just not familiar with the details here but I'll research it.

Do you by chance know if cmake-based *installation* ever worked in Erin's Box2D code? I'd like to fully support using `cmake` but maybe that's why he moved to using `premake`.

I should know more soon after I've reviewed git history. Thanks for your patience.

**Comment by louis-langholtz** [comment]
Adding what I'm finding here (thinking out loud so-to-speak)...

`UsePlayRho.cmake` had previously been called `UseBox2d.cmake` in the `PlayRho/PlayRho.cmake` file prior to commit cf15e1141a8f517b8a8d0f0bf76865a1f9b27bf8. It was only mentioned in that file in a comment though.

`UsePlayRho.cmake` had previously been called `UseBox2D.cmake` in the `PlayRho/CMakeLists.txt` file prior to commit d8d99b8d33f75cb336deed2741790f9289e1dbcc. In this same commit there seems to be a mention of the file `PlayRho/PlayRho.cmake` having been renamed from its previous name of `PlayRho/UseBox2D.cmake`.

Bingo!

Seems when I renamed things, I accidentally dropped the `Use` portion of the filename in question. I'll push a commit that remedies this shortly.

**Comment by Megaxela** [comment]
Ye, now everything is working fine. But there is another error, as for me. I'll create another issue for it.
I don't know, why Erin moved from `cmake` to `premake` tool for building. But as for me, `cmake` is much more comfortable tool.

**Comment by louis-langholtz** [comment]
"everything is working fine"... That's great news to me! Thank you so much for trying it out again and updating me.

Yes, please create a new issue if it's not the same as this one was/is. Thanks!

Glad `cmake` is preferable for you. I suspect a lot of people feel the same.
