### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#4]
Hi Louis,

I came by this repo through [this answer](https://gamedev.stackexchange.com/a/144950/34569). It looks like a well maintained project for the most part, good job! Maybe I'll try building soon.

I did notice, however that the links to the Changes Document, Building Document, and API Pages are all broken as of now.

**Comment by louis-langholtz** [comment]
Thanks for recognizing this!! Working on fixing it now.

**Comment by louis-langholtz** [comment]
I believe all the links in the README are fixed now with commit 1e841e78b71a6157e042c15d291b5f98f341cf26. Please re-open this issue if you find anymore in this README that are broken.

I also found some links in other files that weren't quite right and have fixed those I believe too.

Thanks again for pointing the problems out!
