### ISSUE TITLE
Visual Studio 2017 Testbed Build Error C2662

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#40]
### Expected/Desired Behavior or Experience:
Testbed builds successfully from CMake-generated build and provided VS solution.

### Actual Behavior:
Build fails with compiler errors [C2662](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2662?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2662)%26rd%3Dtrue) in both Testbed/Tests/HeavyOnLight.cpp and similar code within UnitTests/World.cpp : 

```
Error	C2662	'playrho::BodyDef &playrho::BodyDef::UseLocation(playrho::Length2D) noexcept': cannot convert 'this' pointer from 'const playrho::BodyDef' to 'playrho::BodyDef &'	Testbed	c:\path\to\playrho\testbed\Tests\HeavyOnLight.hpp	34
```
Line 34 is:
```
        const auto upperBodyDef = BodyDef{bd}.UseLocation(Vec2(0.0f, 6.0f) * Meter);
```

Similar errors occur where `lowerBodyDef`, `smallerDiscConf`, and `biggerDiscConf`. There are similar compiler errors in `World.cpp`. These errors cascade into other compiler errors, so I'll post those as issues if resolving these does not fix them.

I'm not entirely sure, but I think the [today's visual studio update](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#C++ToolsetLibs15) may have something to do with this error.

### Steps to Reproduce the Actual Behavior:
Build the CMake-generated VS2017 project or the supplied project.

**Comment by louis-langholtz** [comment]
Odd. Does this problem also occur if building from the Visual Studio solution that PlayRho provides, or only when building using CMake?

Sounds at first like the Visual Studio (VS) update effectively changed whether builders could be used in C++ `constexpr` code. But if that's the case then the statement before line 34 shouldn't have compiled either.

**Comment by NauticalMile64** [comment]
It happens with both the CMake-generated build and the provided VS solution.

VS2017 15.3 did contain [updates](https://blogs.msdn.microsoft.com/vcblog/2017/05/10/c17-features-in-vs-2017-3/) for the behavior of `constexpr`. After this change, [a compiler bug](https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c17-features-and-stl-fixes-in-vs-2017-15-3/) was identified by a MS developer (see Billy O'Neal's reply to Micheal's comment). Billy also confirms that this is the same bug [mentioned here](https://developercommunity.visualstudio.com/comments/76215/view.html), which reveals the incorrect behavior of `constexpr` struct member functions. I'm optimistic that the upcoming bugfix will resolve this issue as well, but in the interim, anyone who updates to VS 15.3 will be unable to compile the testbed. 😒 

@louis-langholtz Is this current repo passing the automated tests still? Are they using VS < 15.3?

**Comment by louis-langholtz** [comment]
For reference purposes... looks like AppVeyor currently uses [Visual Studio Community 2017 version 15.2](https://www.appveyor.com/docs/build-environment/#visual-studio-2017) for its "standard" Visual Studio 2017 build worker image.

**Comment by louis-langholtz** [comment]
Update:

I see this now with the UnitTests on Windows using 15.2. Meanwhile, 15.2 has no problem with line 37-39 of `HelloWorld.cpp`:

    const auto groundBody = world.CreateBody(playrho::BodyDef{}.UseLocation(playrho::Length2D{
        playrho::Real(0) * playrho::Meter, playrho::Real(-10) * playrho::Meter
    }));

If I changed the syntax of line 34 of `Testbed/Tests/HeavyOnLight.hpp` to:

    const auto upperBodyDef = BodyDef(bd).UseLocation(Vec2(0.0f, 6.0f) * Meter);

Then the error message goes away.

**Comment by louis-langholtz** [comment]
Appears this problem is isolated to MSVS C++. At least it doesn't show up with clang 4.0, gcc 7.2, nor icc 17. See [code snippet test](https://godbolt.org/g/5n5tc6) on godbolt.

**Comment by NauticalMile64** [comment]
Yeah, I'm pretty sure it's a compiler bug specific to visual studio. That's very strange it appears in 15.2 (unless appveyor is using one of the 15.3 release candiadates???). As a side note, they released 15.3.1 on Aug 18, but the bugfix was not included 😞 .

**Comment by louis-langholtz** [comment]
Give it a try again when you can. I think I worked around the problem with my last two commits.

**Comment by NauticalMile64** [comment]
Those commits did the trick, thanks!

**Comment by louis-langholtz** [comment]
Great to hear! :tada: :fireworks: :balloon: 😄
