### ISSUE TITLE
"vector<bool> subscript out of range" in WorldImpl

### ISSUE THREAD

**Issue by Dragopapa** [louis-langholtz/PlayRho#422]
![subscripterror](https://user-images.githubusercontent.com/11604193/134545144-528556c8-d511-42a7-8314-bedd1f6db1b1.png)

**Comment by louis-langholtz** [comment]
Thank you for reporting this!

What release of the codebase was this with? Or what was the latest commit hash?

**Comment by Dragopapa** [comment]
It was with the latest master branch (fa70fd711ce02c21aab00ee933d18fbf82032e3a).
