### ISSUE TITLE
No Text Displayed in the testbed Window

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#5]
I built the project on Windows 7 using the provided solution file (VS Community 2017). Everything worked pretty smooth. I can pull the boxes around, etc... except I don't see any text onscreen when I run the testbed as shown in the image below. I think the buttons and sliders are working properly (the very bottom right button exits the program at very least).

I also have a few other constructive comments about the project in general that don't really deserve to have issues opened for each of them. Is there another place the project can be discussed? Alternatively, feel free to send me an email!

![testbed_no_text](https://user-images.githubusercontent.com/4357024/28343204-2db85d1e-6bea-11e7-918e-7e26d68942ec.png)

**Comment by NauticalMile64** [comment]
I just noticed that when I run from the command line, it gives the errors:

```
PlayRho 3.0.0 (asserts=on, Real=float), OpenGL 3.3.0 NVIDIA 376.51, GLSL 3.30 NV
IDIA via Cg compiler
Attempting to load font from "C:\SomePath\PlayRho\Build
\vs2017\bin\x32\Debug/../../Testbed/Data/DroidSans.ttf",  failed.
Attempting to load font from "C:\SomePath\PlayRho\Build
\vs2017\bin\x32\Debug/../Data/DroidSans.ttf",  failed.
Attempting to load font from "C:\SomePath\PlayRho\Build
\vs2017\bin\x32\Debug/Data/DroidSans.ttf",  failed.
Attempting to load font from "C:\SomePath\PlayRho\Build
\vs2017\bin\x32\Debug/../../../../Data/DroidSans.ttf",  failed.
Attempting to load font from "C:\SomePath\PlayRho\Build
\vs2017\bin\x32\Debug/./DroidSans.ttf",  failed.
```

So it can't find the font. I ran a search and the font is at:

```
C:\SomePath\PlayRho\Testbed\Data\DroidSans.ttf
```

Everything works fine if I move the file to:

```
C:\SomePath\PlayRho\Build\vs2017\bin\x32\Data\DroidSans.ttf
```

I'm not sure how those search paths are decided, but they're missing the mark on my machine.

**Comment by louis-langholtz** [comment]
Sorry about this text display issue.

Admittedly this issue comes up too often IMO. Commit a266e7657288c5c962b6216949449755296dda2f (which I've pushed to the repo now) should remedy this once and for all.

As for comments about the project, I'd love those! You're welcome to open as many issues as you have suggestions, enhancement ideas, nits-to-pick, bugs or any other separable concepts. I don't know of other places within GitHub that the project can be discussed but I'll send you an email like you suggested.

**Comment by NauticalMile64** [comment]
Fix works. Thanks!
