### ISSUE TITLE
Build Checks are run even when Inconsequential files are changed

### ISSUE THREAD

**Issue by NauticalMile64** [louis-langholtz/PlayRho#55]
### Expected/Desired Behavior or Experience:
The build system skips prs where no source code files were modified.

### Actual Behavior:
I just noticed when I submitted pr #54 that the system is running the build tests (and I assume it's going to run coveralls and the benchmark tests afterward). The only change I made was to a documentation (.md) file. I know the consequences for us (the maintainers) are minimal, but this seems like a poor use of public resources.

### Steps to Reproduce the Actual Behavior:
Submit a pr with only documentation changes.

**Comment by louis-langholtz** [comment]
Agreed. I'd looked into this before too.

`[skip ci]` or `[ci skip]` can manually be used within git commit messages to skip CI building (for both CI systems).

AppVeyor has a [web page on commits filtering](https://www.appveyor.com/docs/how-to/filtering-commits/). It says `[skip appveyor]` in the commit message will skip AppVeyor builds.

I think we'd both prefer a more automatic approach though that filtered based on pre-configured file names that are configured in the `appveyor.yml` file. AppVeyor has that capability (see previous link).  Unfortunately, Travis-CI doesn't currently seem to have support for this (see [Exclude files from triggering a build](https://github.com/travis-ci/travis-ci/issues/6301)).

So not sure where to go with this for the moment except to add filtering for AppVeyor and just have to live with Travis-CI continuing for now.

**Comment by NauticalMile64** [comment]
Alright, that makes sense. I didn't notice those tags before. I'll use them for docs changes from now on. I'll leave it up to you whether to close this issue or not.

**Comment by louis-langholtz** [comment]
I like this issue and want to keep it open. I'll update the AppVeyor config file to filter some file changes out for now and then keep this open till I do the same for Travis-CI (after Travis-CI makes something like this available).

**Comment by louis-langholtz** [comment]
Also note that doc changes may still have need or want of being CI managed like for building/updating the `gh-pages` branch after every PR. Just something else I need to keep in mind about this issue.

**Comment by louis-langholtz** [comment]
I'm thinking that Travis-CI runs for more branches than it needs to. Perhaps `.travis.yml` file needs to be updated to un-comment the `branches: only:` info.

**Comment by louis-langholtz** [comment]
Closing this now. If/when Travis-CI updates its filtering capacity this should get revisited again.
