### ISSUE TITLE
Incorrect manifolds when deserializing/recreating the World state

### ISSUE THREAD

**Issue by opera-aberglund** [louis-langholtz/PlayRho#567]
I encountered an issue when deserializing and recreating the `World` state where the result of `SameTouching` in the `operator==` for the `AabbTreeWorld` returned false.  Investigating it more, I found that the cause of the inequality was that the `normalImpulse` and `tangentImpulse` of the manifolds in the world copy were always 0. This was the only thing differing between the objects, as everything else (including the contacts) were equal. 

### Steps to Reproduce:
I used a simple test of dropping a box (with area density > 0) on a flat surface. When the box landed on the surface, the contacts were recreated correctly in the copied world, but the manifolds differed.

**Comment by louis-langholtz** [comment]
Thank you for reporting this.

Sounds like the world copy construction or the copy assignment code isn't copying the manifold state for those properties. Sorry about this.

I have unit test code for checking the copy functionality but perhaps it's not checking this info.

I'll investigate & report back on this.

**Comment by opera-aberglund** [comment]
> I'm not clear that's a bug. Is your code transferring this state from source to destination?

Actually it wasn't. I just assumed this would be recreated automatically. I tested now to just serialize the impulses and set them manually and it seems to work. Thanks for the help though! I'm closing this issue.
