### ISSUE TITLE
Just two very similar functions

### ISSUE THREAD

**Issue by opera-aberglund** [louis-langholtz/PlayRho#569]
I might be a bit nit-picky here, but aren't these two basically the same function?

https://github.com/louis-langholtz/PlayRho/blob/1f8b0432748e970f7068611019da949dcaa60dd0/Library/include/playrho/d2/Manifold.hpp#L379

https://github.com/louis-langholtz/PlayRho/blob/1f8b0432748e970f7068611019da949dcaa60dd0/Library/include/playrho/d2/Manifold.hpp#L396

**Comment by louis-langholtz** [comment]
Same functionality, yes. Different input parameters of course.

**Comment by louis-langholtz** [comment]
I feel bugged that they have different names. I think I'd also prefer to see one refactored into being a free function.

**Comment by louis-langholtz** [comment]
Thank you for pointing this out!

**Comment by louis-langholtz** [comment]
Some updates on the changes I'm working on for this:

- I'm looking at renaming the `Get*Impulses` and `Set*Impulses` functions to `GetImpulses` and `SetImpulses` respectively. So while there will still be two similar functions, they'll both be named `SetImpulses` and just take different parameters.
- I've decided to try and do some of the refactoring of the `Manifold` that I'd previous made a project for. So far that's included the above mentioned renames, and also removing some unused interfaces from `Manifold`. Internally, I've also been reducing the syntax that at least for me seems more readable.
- I'm considering removing two bytes of state from `Manifold` and encoding that info without that memory.
