### ISSUE TITLE
Convert files to the same line endings

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#69]
### Expected/Desired Behavior or Experience:
All C++ source and header files use the same line endings. Preferably the standard Linux/Unix line ending. Git is configured to enforce this line ending. The editor configurations are similarly setup.

### Actual Behavior:
I believe some files C++ files have non-compliant line endings and is causing messier diff's in commits.

**Comment by louis-langholtz** [comment]
Incidentally, I'm dreading fixing this. I suspect there will be lots of changed files with only line ending differences and may take a few tries to get everything in sync again.

**Comment by Hexlord** [comment]
Do you mind me doing such PR? What do you mean by getting everything in sync?

**Comment by louis-langholtz** [comment]
@Hexlord Sorry, I just noticed your comment today. I'd already checked the file line endings. All of the PlayRho library .cpp and .hpp files are already in the desired line endings. There are some inconsistencies in other files though. In any case, I'd like to finish taking care of this. You're welcome to offer feedback/suggestions for improvement.

**Comment by Hexlord** [comment]
@louis-langholtz That is some strange stuff I happen to see often working with git via SourceTree and Github for Windows. [Seems](https://stackoverflow.com/a/11603521) like the time to stop using programs and stick to the command line.

**Comment by louis-langholtz** [comment]
So among other changes, I followed the [Refreshing a repository after changing line endings](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings) instructions in generating the diffs in PR #101. Hopefully this corrects the mashup of line endings in files like `HelloWorld/CMakeLists.txt` (that uses both Linux and Windows line ending styles). I won't know for sure though till I merge this PR into the master branch and then pull update my local master branch. This is essentially the syncing I'd mentioned previously.

**Comment by louis-langholtz** [comment]
Cool. Things look better now in terms of line endings appearing consistent now.
