### ISSUE TITLE
Wrong spelling in comments

### ISSUE THREAD

**Issue by Hexlord** [louis-langholtz/PlayRho#74]
### Expected/Desired Behavior or Experience:
Right spelling being used in comments

### Actual Behavior:
Some misspellings occur in comments

### Todo:
Manually look through files and fix misspellings

### Related issues:
[Want command line runnable spell checking tool for C++ comments](https://github.com/louis-langholtz/PlayRho/issues/65)

**Comment by louis-langholtz** [comment]
@Hexlord Is this something you're interested in working on in terms of making any Pull Requests for? I know you'd found some spelling mistakes in the past that were in comments. If you make the pull request have only changes that pertains to spelling in comments and they pass the PR checks these should be easy to get integrated and resolve this issue.

**Comment by Hexlord** [comment]
@louis-langholtz Sure will, being kinda swamped with work atm, but I think I will finish pullrequest till next week, same with unnecessary includes. Happy to see you pushing the beta launch (: .

**Comment by Hexlord** [comment]
Not sure this can be entirely resolved till Beta Launch, [tools](https://github.com/louis-langholtz/PlayRho/issues/65) must be integrated to allow resolving this issue. Commonly changed files are manually checked though, and look fine now.

**Comment by louis-langholtz** [comment]
@Hexlord Thanks for doing this stuff! I agree about the need for automating the spelling. Closing this issue now since we also have issue #65 (like you referenced) to move forward on this into the future.
